google:
  api_key: none

foursquare:
  user: bcm@maz.org
  password: @replace@

feed_monster:
  sources:
    - name: foursquare
      class_name: Checkin
#      feed:
#        url: http://feeds.foursquare.com/history/2a5ca48c03859a8abbf2cc358411893c.rss
      api:
        method_name: load_checkins
    - name: google_reader
      class_name: Link
      feed:
        url: http://www.google.com/reader/public/atom/user/17474520617057440479/state/com.google/broadcast
    - name: twitter
      class_name: Tweet
      feed:
        url: http://twitter.com/statuses/user_timeline.atom?id=bcm&count=10
        since_param: since_id
    - name: delicious
      class_name: Bookmark
      feed:
        url: http://feeds.delicious.com/v2/rss/bcm?count=10
    - name: tumblr
      class_name: Tumblog
      feed:
        url: http://bcm.tumblr.com/rss
    - name: youtube
      class_name: Video
      feed:
        url: http://gdata.youtube.com/feeds/base/users/bmoseley/favorites
    - name: flickr
      class_name: Photo
      feed:
        url: http://api.flickr.com/services/feeds/photos_public.gne?id=20674645@N00&lang=en-us&format=rss_200